import MarkdownRenderer from './MarkdownRenderer'

const testMarkdown = `
# Executive Summary

This is a **competitive intelligence report** for *OpenAI*. Here are the key findings:

## Key Findings

1. **Market Position**: OpenAI is a leading AI company
2. **Products**: 
   - ChatGPT
   - GPT-4
   - DALL-E
3. **Strategic Advantages**:
   - First-mover advantage in conversational AI
   - Strong partnerships with Microsoft
   - Continuous innovation pipeline

### Technical Capabilities

OpenAI demonstrates strong capabilities in:

- Large Language Models (LLMs)
- Multimodal AI systems
- API development and deployment

> **Note**: This analysis is based on publicly available information as of the analysis date.

## Strategic Recommendations

### Immediate Actions
- Monitor OpenAI's API pricing changes
- Track new product launches
- Analyze competitive responses

### Long-term Strategy
- Develop differentiated AI offerings
- Build strategic partnerships
- Invest in proprietary data advantages

---

*Report generated by Multi-Agent Competitive Intelligence System*
`

export default function MarkdownTest() {
  return (
    <div className="max-w-4xl mx-auto p-8">
      <h2 className="text-2xl font-bold mb-4">Markdown Rendering Test</h2>
      <div className="bg-gray-50 p-6 rounded-lg">
        <MarkdownRenderer content={testMarkdown} />
      </div>
    </div>
  )
}